import os
import re
from collections import OrderedDict


# ── CONFIG ── adjust these two paths ──────────────────────────────────────────
OBJ_FILE   = "assets/Cheops/Cheops.obj"
ASSET_DIR  = os.path.dirname(OBJ_FILE)   # same folder as the .obj
# ──────────────────────────────────────────────────────────────────────────────

# ── TEXTURE MAPPING ───────────────────────────────────────────────────────────
# Map each usemtl name → texture JPG filename.
# Based on your 4 material names and 5 texture files:
#   blinn3SG        → main body texture group 1
#   blinn1SG        → main body texture group 2  (solar panel area)
#   blinn1SG1       → body panels 3 & 4
#   initialShadingGroup → miscellaneous / default grey parts
TEXTURE_MAP = {
    "blinn3SG":             "Cheops-MappedTexture1.jpg",
    "blinn1SG":             "Cheops-SolarPanels_FrontBackSides.jpg",
    "blinn1SG1":            "Cheops-MappedTexture2.jpg",
    "initialShadingGroup":  "Cheops-MappedTexture3.jpg",
}

# Material physical properties per material
# (Ka=ambient, Kd=diffuse, Ks=specular, Ns=shininess, illum=illumination model)
MATERIAL_PROPS = {
    "blinn3SG": {
        "Ka": "1.0 1.0 1.0",
        "Kd": "1.0 1.0 1.0",
        "Ks": "0.3 0.3 0.3",
        "Ns": "50.0",
        "illum": "2",
    },
    "blinn1SG": {
        "Ka": "1.0 1.0 1.0",
        "Kd": "1.0 1.0 1.0",
        "Ks": "0.5 0.5 0.5",   # solar panels are more reflective
        "Ns": "80.0",
        "illum": "2",
    },
    "blinn1SG1": {
        "Ka": "1.0 1.0 1.0",
        "Kd": "1.0 1.0 1.0",
        "Ks": "0.3 0.3 0.3",
        "Ns": "50.0",
        "illum": "2",
    },
    "initialShadingGroup": {
        "Ka": "0.5 0.5 0.5",
        "Kd": "0.5 0.5 0.5",
        "Ks": "0.2 0.2 0.2",
        "Ns": "25.0",
        "illum": "2",
    },
}
# ──────────────────────────────────────────────────────────────────────────────


def extract_usemtl_names(obj_path):
    """
    Parse the .obj and return:
      - names:  list of unique material names (preserving first-appearance order)
      - counts: dict of {material_name: number_of_appearances}
    """
    counts  = OrderedDict()
    pattern = re.compile(r"^usemtl\s+(\S+)", re.MULTILINE)

    with open(obj_path, "r", errors="replace") as f:
        for line in f:
            m = pattern.match(line.strip())
            if m:
                name = m.group(1)
                if name not in counts:
                    counts[name] = 0
                counts[name] += 1

    names = list(counts.keys())
    count = list(counts.values())
    return names, count


def generate_mtl(material_names, texture_map, material_props, out_path):
    lines = ["# Cheops.mtl — auto-generated by generate_mtl.py",
             "# Place alongside Cheops.obj and all texture JPGs",
             ""]

    for name in material_names:
        texture = texture_map.get(name)
        props   = material_props.get(name, {
            "Ka": "1.0 1.0 1.0",
            "Kd": "1.0 1.0 1.0",
            "Ks": "0.2 0.2 0.2",
            "Ns": "30.0",
            "illum": "2",
        })

        lines.append(f"newmtl {name}")
        lines.append(f"Ka {props['Ka']}")
        lines.append(f"Kd {props['Kd']}")
        lines.append(f"Ks {props['Ks']}")
        lines.append(f"Ns {props['Ns']}")
        lines.append("d 1.0")
        lines.append(f"illum {props['illum']}")
        if texture:
            lines.append(f"map_Kd {texture}")
        else:
            # No texture assigned — warn but still write a valid material block
            print(f"  [WARNING] No texture mapped for material '{name}' — using colour only.")
        lines.append("")   # blank line between materials

    with open(out_path, "w") as f:
        f.write("\n".join(lines))

    print(f"[OK] Written: {out_path}")
    return lines


def patch_obj_mtllib(obj_path, mtl_filename):
    """Ensure the .obj has 'mtllib <filename>' at the top."""
    with open(obj_path, "r", errors="replace") as f:
        content = f.read()

    mtllib_line = f"mtllib {mtl_filename}"

    if "mtllib" in content:
        # Replace existing mtllib line
        content = re.sub(r"^mtllib\s+\S+", mtllib_line, content, flags=re.MULTILINE)
        print(f"[OK] Replaced existing mtllib line in {obj_path}")
    else:
        # Prepend it before the first non-comment line
        lines = content.split("\n")
        insert_idx = 0
        for i, line in enumerate(lines):
            if not line.startswith("#") and line.strip():
                insert_idx = i
                break
        lines.insert(insert_idx, mtllib_line)
        content = "\n".join(lines)
        print(f"[OK] Inserted mtllib line into {obj_path}")

    with open(obj_path, "w") as f:
        f.write(content)


# ── MAIN ──────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print(f"Reading OBJ: {OBJ_FILE}")

    # Step 1 — extract unique material names from .obj
    material_names, count = extract_usemtl_names(OBJ_FILE)
    print(f"\nFound {len(material_names)} unique material(s):")
    for n, num in zip(material_names, count):
        tex = TEXTURE_MAP.get(n, "[NO TEXTURE ASSIGNED]")
        print(f"  {n:30s} {num} → {tex}")

    # Step 2 — generate .mtl file
    mtl_filename = "Cheops.mtl"
    mtl_path     = os.path.join(ASSET_DIR, mtl_filename)
    print(f"\nGenerating MTL: {mtl_path}")
    generate_mtl(material_names, TEXTURE_MAP, MATERIAL_PROPS, mtl_path)

    # Step 3 — patch .obj to reference the new .mtl
    print(f"\nPatching OBJ to reference {mtl_filename}...")
    patch_obj_mtllib(OBJ_FILE, mtl_filename)

    print("\n✅ Done! Your asset directory should now contain:")
    print(f"   {ASSET_DIR}/")
    print(f"   ├── Cheops.obj              (patched with mtllib reference)")
    print(f"   ├── Cheops.mtl              (newly generated)")
    print(f"   ├── Cheops-MappedTexture1.jpg") #11
    print(f"   ├── Cheops-MappedTexture2.jpg") #7
    print(f"   ├── Cheops-MappedTexture3.jpg") #6
    print(f"   ├── Cheops-MappedTexture4.jpg") #8
    print(f"   └── Cheops-SolarPanels_FrontBackSides.jpg") #5
